# Generated by Django 5.2.1 on 2025-06-07 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrooms', '0003_hotelroom_room_number_alter_roomreservations_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='room_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='roomreservations',
            name='room',
            field=models.ForeignKey(db_column='room_number', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotelrooms.hotelroom', to_field='room_number'),
        ),
    ]
