# Generated by Django 5.2.1 on 2025-06-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrooms', '0004_alter_hotelroom_room_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomreservations',
            name='room',
        ),
        migrations.AddField(
            model_name='roomreservations',
            name='room_number',
            field=models.ForeignKey(db_column='room_number', default=401, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotelrooms.hotelroom'),
            preserve_default=False,
        ),
    ]
