# Generated by Django 5.2.1 on 2025-06-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrooms', '0005_remove_roomreservations_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomreservations',
            old_name='room_number',
            new_name='room',
        ),
    ]
