# Generated by Django 5.2.1 on 2025-06-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomreservations',
            old_name='room_id',
            new_name='room',
        ),
    ]
