# Generated by Django 5.2.1 on 2025-06-07 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrooms', '0002_rename_room_id_roomreservations_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='room_number',
            field=models.CharField(default=400, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomreservations',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotelrooms.hotelroom'),
        ),
    ]
